#!/usr/bin/env python3
"""Generate `docs/LICENSES.md` from what is actually on disk (plan §7.10).

A licence claim a reviewer can disprove with one `pip show` is a liability, so nothing in
the tables here is typed. The rows come from:

  * every wheel in `wheelhouse/`: the licence the wheel DECLARES in its own METADATA
    (`cva.bundle._licence`), with its sha256;
  * the vendored model artefacts: `cva.features.vendor.manifest()`, the exact checkpoint
    file and its digest, never the repository;
  * the dashboard's production npm dependencies: `frontend/package-lock.json`;
  * the dashboard's vendored fonts and icons: `cva/web/static/vendor/MANIFEST.json`,
    if `scripts/vendor_web_assets.py` has been run.

The few statements that ARE written by hand — the AGPL decision, the dataset terms — are
the ones §7.10 says must be stated in words, and they are marked as such in the output.

    python scripts/generate_licenses.py            # write docs/LICENSES.md
    python scripts/generate_licenses.py --check    # non-zero if the file is stale
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from cva.bundle import wheel_rows  # noqa: E402
from cva.features import vendor  # noqa: E402

OUT = ROOT / "docs" / "LICENSES.md"
WHEELHOUSE = ROOT / "wheelhouse"
LOCK = ROOT / "frontend" / "package-lock.json"
WEB_VENDOR = ROOT / "cva" / "web" / "static" / "vendor" / "MANIFEST.json"

#: §7.10: quote imagehash's licence from the SOURCE, because its package metadata disagrees
#: with itself (BSD-1 vs BSD-2).
SOURCE_LICENCE_FROM_FILE = {"imagehash"}


def _licence_file_text(wheel: Path) -> str:
    """The first line of the LICENSE file shipped inside a wheel, or ""."""
    with zipfile.ZipFile(wheel) as z:
        for name in z.namelist():
            base = name.rsplit("/", 1)[-1].upper()
            if base.startswith(("LICENSE", "LICENCE", "COPYING")):
                text = z.read(name).decode("utf-8", "replace").strip()
                if text:
                    return " ".join(" ".join(text.splitlines()[:2]).split())[:160]
    return ""


def python_rows() -> list[dict[str, str]]:
    if not WHEELHOUSE.is_dir():
        return []
    rows = []
    for r in wheel_rows(WHEELHOUSE):
        name = str(r["artefact"]).lower()
        licence = str(r["licence"])
        note = ""
        if name in SOURCE_LICENCE_FROM_FILE:
            quoted = _licence_file_text(ROOT / str(r["file"]))
            if quoted:
                note = f"from the shipped LICENSE file: “{quoted}” (the package metadata disagrees with itself)"
        if name == "cleanlab":
            note = "see the statement above"
        rows.append({"name": str(r["artefact"]), "version": str(r["version"]),
                     "licence": licence, "sha256": str(r["sha256"]), "note": note})
    return rows


def model_rows() -> list[dict[str, object]]:
    return vendor.manifest()


def npm_rows() -> list[dict[str, str]]:
    """Production dependencies only: devDependencies build the bundle and do not ship."""
    if not LOCK.is_file():
        return []
    lock = json.loads(LOCK.read_text())
    rows = []
    for path, meta in sorted((lock.get("packages") or {}).items()):
        if not path or meta.get("dev") or meta.get("devOptional"):
            continue
        name = path.split("node_modules/")[-1]
        rows.append({"name": name, "version": str(meta.get("version", "")),
                     "licence": str(meta.get("license") or "not declared in the lockfile")})
    return rows


def web_asset_rows() -> list[dict[str, str]] | None:
    if not WEB_VENDOR.is_file():
        return None
    assets = json.loads(WEB_VENDOR.read_text()).get("assets", {})
    return [{"name": k, "licence": v.get("licence", ""), "sha256": v.get("sha256", ""),
             "path": v.get("path", "")} for k, v in sorted(assets.items())]


HEAD = """# Licences

**Generated by `scripts/generate_licenses.py` from the files that ship.** Do not edit it
by hand: re-run the script, and `--check` in CI fails if this file is stale. Every licence in
the tables below is what the artefact *declares* about itself. That is a declaration, not a
legal opinion, and where a declaration is known to be unreliable the table says so.

## Statements (plan §7.10; the Cleanlab line is generated from its wheel)

{cleanlab}
- **DINOv2** is identified below by the **exact checkpoint file and its sha256**, never by
  its repository. The same repository ships other models (XRay-DINO, Cell-DINO) under a
  non-commercial licence, and naming the repository would claim a licence for files that
  are not ours to claim.
- **`imagehash`**: its licence is quoted from the LICENSE file inside the wheel, because its
  package metadata disagrees with itself (BSD-1 vs BSD-2).
- **Datasets.** COCO is **CC BY 4.0, and attribution is required**. CIFAR-10 and GTSRB are for
  research use. VisDrone and DOTA have **not been verified** and must not enter the demo
  until they are. The selftest and demo corpora are synthetic, generated by `cva.fixtures`,
  and carry no third-party terms.
"""


SWAP = ("It is used in-process by the label-quality detectors, and the isolation point is "
        "`find_label_issues`: a deployment that cannot accept its licence swaps the "
        "implementation behind the `Detector` interface, and nothing outside that call "
        "depends on Cleanlab.")


def cleanlab_statement(rows: list[dict[str, str]]) -> str:
    """Generated from the wheel, because the plan's statement was about an older release.

    The plan (§7.10) says Cleanlab is AGPL-3.0-or-later and must be stated unhedged. That
    was true of earlier releases. What ships is decided by the wheel, and if the wheel says
    otherwise, this file says what the wheel says — and that the plan's line is outdated —
    rather than repeating a licence the artefact does not carry.
    """
    row = next((r for r in rows if r["name"].lower() == "cleanlab"), None)
    if row is None:
        return "- **Cleanlab** is not in this wheelhouse."
    wheel = next(WHEELHOUSE.glob(f"cleanlab-{row['version']}-*.whl"), None)
    shipped = _licence_file_text(wheel) if wheel else ""
    evidence = f"declares `{row['licence']}`" + (
        f" and its LICENSE file begins “{shipped}”" if shipped else "")
    if re.search(r"AGPL|Affero", row["licence"] + shipped, re.I):
        return (f"- **Cleanlab {row['version']} is AGPL-3.0-or-later** (the wheel {evidence}). "
                "The submission ships full source (PS §2.3), which meets the copyleft "
                f"obligation for this submission. {SWAP}")
    return (f"- **Cleanlab {row['version']}**: the wheel {evidence}. The plan (§7.10) "
            "recorded Cleanlab as AGPL-3.0-or-later. That describes earlier releases, not "
            "the one that ships here, so this file states the shipped licence and not the "
            "plan's. Pinning an older release would bring AGPL back, and this section is "
            f"regenerated from the wheel so it would say so. {SWAP}")


def render() -> str:
    py = python_rows()
    out = [HEAD.replace("{cleanlab}", cleanlab_statement(py))]

    out += ["## Model artefacts (vendored)", "",
            "| Artefact | File | Licence | sha256 | Present, digest matches |",
            "|---|---|---|---|---|"]
    for r in model_rows():
        ok = "yes" if r.get("present") and r.get("digest_matches") else "**no**"
        out.append(f"| {r['artefact']} | `{r['file']}` | {r['licence']} | "
                   f"`{str(r['sha256'])[:64]}` | {ok} |")
    out.append("")

    out += ["## Python packages (`wheelhouse/`)", ""]
    if py:
        out += ["| Package | Version | Declared licence | sha256 (first 16) | Note |",
                "|---|---|---|---|---|"]
        for r in py:
            out.append(f"| {r['name']} | {r['version']} | {r['licence']} | "
                       f"`{r['sha256'][:16]}` | {r['note']} |")
    else:
        out.append("*No `wheelhouse/` was present when this file was generated. Run "
                   "`make wheelhouse` and regenerate it; until then this section is "
                   "absent, not empty.*")
    out.append("")

    npm = npm_rows()
    out += ["## Dashboard packages (npm, production only)", "",
            "These are compiled into the static export under `frontend/out/`. Development "
            "dependencies (TypeScript, Tailwind, PostCSS) build the bundle and do not ship.",
            ""]
    if npm:
        out += ["| Package | Version | Declared licence |", "|---|---|---|"]
        out += [f"| {r['name']} | {r['version']} | {r['licence']} |" for r in npm]
    else:
        out.append("*No `frontend/package-lock.json` was present.*")
    out.append("")

    web = web_asset_rows()
    out += ["## Server-rendered view assets (fonts, icons)", ""]
    if web is None:
        out.append("*`scripts/vendor_web_assets.py` has not been run for this build, so no "
                   "fonts or icon files are vendored. The server-rendered views fall back "
                   "to system fonts. No asset is fetched from a CDN at runtime either "
                   "way.*")
    else:
        out += ["| Asset | Path | Licence | sha256 (first 16) |", "|---|---|---|---|"]
        out += [f"| {r['name']} | `{r['path']}` | {r['licence']} | `{r['sha256'][:16]}` |"
                for r in web]
    out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail if docs/LICENSES.md is stale")
    a = ap.parse_args(argv)
    text = render()
    if a.check:
        current = OUT.read_text() if OUT.is_file() else ""
        if current != text:
            print(f"{OUT.relative_to(ROOT)} is stale: run scripts/generate_licenses.py",
                  file=sys.stderr)
            return 1
        print(f"ok: {OUT.relative_to(ROOT)} matches what ships")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    agpl = [r["name"] for r in python_rows() if re.search(r"AGPL", r["licence"], re.I)]
    print(f"wrote {OUT.relative_to(ROOT)}; AGPL packages declared: {agpl or 'none'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
